name: E2E Workflow Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@chauhaidang'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install global xq-infra
        run: npm install -g @chauhaidang/xq-test-infra
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install root dependencies (API server only)
        run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run init tests
        run: npm run test:unit

      - name: build write-service
        run: |
          chmod +x ./build-write-service.sh
          ./build-write-service.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


      - name: Start up environment
        run: | 
          xq-infra generate -f ./test-env
          xq-infra up

      - name: Run e2e tests
        run: npm run test:component:ci

      - name: Stop environment
        run: xq-infra down

      - name: Present tsr
        if: success() || failure()
        working-directory: ./e2e
        run: cat test/component/tsr/report.md >> $GITHUB_STEP_SUMMARY


